apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pu6uo6faf-python 
  janus-idp.io/tekton: pu6uo6faf-python
  backstage.io/kubernetes-id: pu6uo6faf-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pu6uo6faf-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml