apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pu6uo6faf-python
  janus-idp.io/tekton: pu6uo6faf-python
  backstage.io/kubernetes-id: pu6uo6faf-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pu6uo6faf-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
