apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: pu6uo6faf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pu6uo6faf-python 
  name: pu6uo6faf-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pu6uo6faf-python
    weight: 100 
