apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pu6uo6faf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pu6uo6faf-python 
  name: pu6uo6faf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pu6uo6faf-python 
